### ISSUE TITLE
Create GitHub release (git tag)

### ISSUE THREAD

**Issue by favoyang** [5argon/ECSLineRenderer#7]
Hi @5argon ,

Thanks for creating the awesome package. Would please create a github release `v1.0.0`? So the package can be included in upcoming openupm registry ([sneak preview](https://openupm.com)), which is a service that build package directly from git tags that conform semver.

**Comment by 5argon** [comment]
Hi, I think it will not be possible before ECS itself hits 1.0.0 if I would like to adhere to SemVer : P

**Comment by favoyang** [comment]
@5argon Thanks for the reply!

Let me re-propose: I would like to request you to do some version control of the project regularly to release the GitHub releases against the current version number of your package.json. This will benefits the OpenUPM platform (beta) to be able to fetch your releases and bundle packages and hosting on the platform.

With semantic version, 1.1.0 and 0.1.0 are no different in meaning, so logically we should be worry about to sync the version with ECS itself? Or maybe I'm misunderstanding on something.

With some tool like https://github.com/marketplace/actions/action-for-semantic-release, it can be completed automated on CI (analyze commit message, generate changelog, bump version, commit back to master, create GitHub release...) . i.e. https://github.com/MirrorNG/MirrorNG leverages the tool to manage their upm package.

If this goes well I will like to add other your popular packages to the platform later.

**Comment by 5argon** [comment]
So you mean I could create a release with 0.x.x and your tool would be able to pick it up as well?

I mean I cannot put the first number in 1.x.x because then every breaking change will have to bump the first number. Currently ECS is on 0.x and have a chance to break at every update. To catch up with ECS, while ECS keeps going up in 0.x I have to bump the first number constantly since it is already non zero. If I could stay in 0 first number, then I can keep it in the developement flux state like ECS and could freely introduce breaking changes without the first number increasing.

**Comment by favoyang** [comment]
> So you mean I could create a release with 0.x.x and your tool would be able to pick it up as well?

Yes. The tool watches any git that is semver. So 0.x.x and 1.x.x are no difference for the build pipelines.

> Currently ECS is on 0.x and have a chance to break at every update. To catch up with ECS, while ECS keeps going up in 0.x I have to bump the first number constantly since it is already non zero. 

I feel some emotion connections between your package and the "com.unity.entities" (0.4.x), to keep the first major version string same. I even don't think that is very necessary, as an audience of  your package, I would expect the "breaking change" is about your api (but could include the adoption for breaking changes of `com.unity.entities`).

But you've made your point. And I respect that. So shall we change the package.json version to 0.x.y and make a GitHub release?

(The [action-for-semantic-release]( https://github.com/marketplace/actions/action-for-semantic-release) thing is worth to checkout, but it takes time to adopt.)

**Comment by favoyang** [comment]
Hi @5argon 

I noticed this was closed, but no git tags was release. Do you still want to change your version of `package.json` to 0.x.y (is 1.0.0 for now), and make a GitHub Releases?
